//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Conf.Gameplay
{
public sealed partial class EquipInfo :  Bright.Config.BeanBase 
{
    public EquipInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Part = _buf.ReadInt();
        GradeLevel = _buf.ReadInt();
        LevelLimit = _buf.ReadInt();
        Desc = _buf.ReadString();
        Icon = _buf.ReadString();
        PostInit();
    }

    public static EquipInfo DeserializeEquipInfo(ByteBuf _buf)
    {
        return new Conf.Gameplay.EquipInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 部位
    /// </summary>
    public int Part { get; private set; }
    /// <summary>
    /// 品阶
    /// </summary>
    public int GradeLevel { get; private set; }
    /// <summary>
    /// 等级限制
    /// </summary>
    public int LevelLimit { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 图标
    /// </summary>
    public string Icon { get; private set; }

    public const int __ID__ = 1388047904;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Part:" + Part + ","
        + "GradeLevel:" + GradeLevel + ","
        + "LevelLimit:" + LevelLimit + ","
        + "Desc:" + Desc + ","
        + "Icon:" + Icon + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}