//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Conf.Gameplay
{
public sealed partial class EquipQualityInfo :  Bright.Config.BeanBase 
{
    public EquipQualityInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Value = _buf.ReadInt();
        InitalAttrCount = _buf.ReadInt();
        InitalAttrLimitCount = _buf.ReadInt();
        PostInit();
    }

    public static EquipQualityInfo DeserializeEquipQualityInfo(ByteBuf _buf)
    {
        return new Conf.Gameplay.EquipQualityInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 品质系数
    /// </summary>
    public int Value { get; private set; }
    /// <summary>
    /// 初始词条数量下限
    /// </summary>
    public int InitalAttrCount { get; private set; }
    /// <summary>
    /// 初始词条数量上限
    /// </summary>
    public int InitalAttrLimitCount { get; private set; }

    public const int __ID__ = 1075598491;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Value:" + Value + ","
        + "InitalAttrCount:" + InitalAttrCount + ","
        + "InitalAttrLimitCount:" + InitalAttrLimitCount + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}