//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Conf.Gameplay
{
public sealed partial class HeroInfo :  Bright.Config.BeanBase 
{
    public HeroInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Skill = _buf.ReadInt();
        ModelName = _buf.ReadString();
        PostInit();
    }

    public static HeroInfo DeserializeHeroInfo(ByteBuf _buf)
    {
        return new Conf.Gameplay.HeroInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 英雄名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 主动技能 ID
    /// </summary>
    public int Skill { get; private set; }
    /// <summary>
    /// 模型资源名
    /// </summary>
    public string ModelName { get; private set; }

    public const int __ID__ = -1440437658;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Skill:" + Skill + ","
        + "ModelName:" + ModelName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}