//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Conf.Gameplay
{
public sealed partial class RoguelikeDropInfo :  Bright.Config.BeanBase 
{
    public RoguelikeDropInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        Rate = _buf.ReadInt();
        Name = _buf.ReadString();
        PostInit();
    }

    public static RoguelikeDropInfo DeserializeRoguelikeDropInfo(ByteBuf _buf)
    {
        return new Conf.Gameplay.RoguelikeDropInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 掉落类型
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 掉落概率
    /// </summary>
    public int Rate { get; private set; }
    /// <summary>
    /// 掉落名称
    /// </summary>
    public string Name { get; private set; }

    public const int __ID__ = 1532956400;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Rate:" + Rate + ","
        + "Name:" + Name + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}