//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Conf.Gameplay
{
public sealed partial class SkillComposeInfo :  Bright.Config.BeanBase 
{
    public SkillComposeInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        StaticSkill = _buf.ReadInt();
        DynamicSkill = _buf.ReadInt();
        PostInit();
    }

    public static SkillComposeInfo DeserializeSkillComposeInfo(ByteBuf _buf)
    {
        return new Conf.Gameplay.SkillComposeInfo(_buf);
    }

    /// <summary>
    /// 合成 ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 被动技能ID
    /// </summary>
    public int StaticSkill { get; private set; }
    /// <summary>
    /// 动态技能ID
    /// </summary>
    public int DynamicSkill { get; private set; }

    public const int __ID__ = -2140851475;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "StaticSkill:" + StaticSkill + ","
        + "DynamicSkill:" + DynamicSkill + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}