//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;



 
public partial class Tables
{
    public Conf.Gameplay.ParkourInfos ParkourInfos {get; }
    public Conf.Gameplay.RoguelikeInfos RoguelikeInfos {get; }
    public Conf.Gameplay.AttributeInfos AttributeInfos {get; }
    public Conf.Gameplay.StageInfos StageInfos {get; }
    public Conf.Gameplay.StageGroupInfos StageGroupInfos {get; }
    public Conf.Gameplay.HeroInfos HeroInfos {get; }
    public Conf.Gameplay.MonsterInfos MonsterInfos {get; }
    public Conf.Gameplay.RoguelikeDropInfos RoguelikeDropInfos {get; }
    public Conf.Gameplay.SkillInfos SkillInfos {get; }
    public Conf.Gameplay.SkillComposeInfos SkillComposeInfos {get; }
    public Conf.Gameplay.EvolutionOptionInfos EvolutionOptionInfos {get; }
    public Conf.Gameplay.ItemInfos ItemInfos {get; }
    public Conf.Gameplay.EquipInfos EquipInfos {get; }
    public Conf.Gameplay.EquipQualityInfos EquipQualityInfos {get; }
    public Conf.Gameplay.EquipAttributeInfos EquipAttributeInfos {get; }
    public Conf.Gameplay.EquipAttributeWeightInfos EquipAttributeWeightInfos {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        ParkourInfos = new Conf.Gameplay.ParkourInfos(loader("Conf.Gameplay.ParkourInfo")); 
        tables.Add("Conf.Gameplay.ParkourInfos", ParkourInfos);
        RoguelikeInfos = new Conf.Gameplay.RoguelikeInfos(loader("Conf.Gameplay.RoguelikeInfo")); 
        tables.Add("Conf.Gameplay.RoguelikeInfos", RoguelikeInfos);
        AttributeInfos = new Conf.Gameplay.AttributeInfos(loader("Conf.Gameplay.AttributeInfo")); 
        tables.Add("Conf.Gameplay.AttributeInfos", AttributeInfos);
        StageInfos = new Conf.Gameplay.StageInfos(loader("Conf.Gameplay.StageInfo")); 
        tables.Add("Conf.Gameplay.StageInfos", StageInfos);
        StageGroupInfos = new Conf.Gameplay.StageGroupInfos(loader("Conf.Gameplay.StageGroupInfo")); 
        tables.Add("Conf.Gameplay.StageGroupInfos", StageGroupInfos);
        HeroInfos = new Conf.Gameplay.HeroInfos(loader("Conf.Gameplay.HeroInfo")); 
        tables.Add("Conf.Gameplay.HeroInfos", HeroInfos);
        MonsterInfos = new Conf.Gameplay.MonsterInfos(loader("Conf.Gameplay.MonsterInfo")); 
        tables.Add("Conf.Gameplay.MonsterInfos", MonsterInfos);
        RoguelikeDropInfos = new Conf.Gameplay.RoguelikeDropInfos(loader("Conf.Gameplay.RoguelikeDropInfo")); 
        tables.Add("Conf.Gameplay.RoguelikeDropInfos", RoguelikeDropInfos);
        SkillInfos = new Conf.Gameplay.SkillInfos(loader("Conf.Gameplay.SkillInfo")); 
        tables.Add("Conf.Gameplay.SkillInfos", SkillInfos);
        SkillComposeInfos = new Conf.Gameplay.SkillComposeInfos(loader("Conf.Gameplay.SkillComposeInfo")); 
        tables.Add("Conf.Gameplay.SkillComposeInfos", SkillComposeInfos);
        EvolutionOptionInfos = new Conf.Gameplay.EvolutionOptionInfos(loader("Conf.Gameplay.EvolutionOptionInfo")); 
        tables.Add("Conf.Gameplay.EvolutionOptionInfos", EvolutionOptionInfos);
        ItemInfos = new Conf.Gameplay.ItemInfos(loader("Conf.Gameplay.ItemInfo")); 
        tables.Add("Conf.Gameplay.ItemInfos", ItemInfos);
        EquipInfos = new Conf.Gameplay.EquipInfos(loader("Conf.Gameplay.EquipInfo")); 
        tables.Add("Conf.Gameplay.EquipInfos", EquipInfos);
        EquipQualityInfos = new Conf.Gameplay.EquipQualityInfos(loader("Conf.Gameplay.EquipQualityInfo")); 
        tables.Add("Conf.Gameplay.EquipQualityInfos", EquipQualityInfos);
        EquipAttributeInfos = new Conf.Gameplay.EquipAttributeInfos(loader("Conf.Gameplay.EquipAttributeInfo")); 
        tables.Add("Conf.Gameplay.EquipAttributeInfos", EquipAttributeInfos);
        EquipAttributeWeightInfos = new Conf.Gameplay.EquipAttributeWeightInfos(loader("Conf.Gameplay.EquipAttributeWeightInfo")); 
        tables.Add("Conf.Gameplay.EquipAttributeWeightInfos", EquipAttributeWeightInfos);

        PostInit();
        ParkourInfos.Resolve(tables); 
        RoguelikeInfos.Resolve(tables); 
        AttributeInfos.Resolve(tables); 
        StageInfos.Resolve(tables); 
        StageGroupInfos.Resolve(tables); 
        HeroInfos.Resolve(tables); 
        MonsterInfos.Resolve(tables); 
        RoguelikeDropInfos.Resolve(tables); 
        SkillInfos.Resolve(tables); 
        SkillComposeInfos.Resolve(tables); 
        EvolutionOptionInfos.Resolve(tables); 
        ItemInfos.Resolve(tables); 
        EquipInfos.Resolve(tables); 
        EquipQualityInfos.Resolve(tables); 
        EquipAttributeInfos.Resolve(tables); 
        EquipAttributeWeightInfos.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        ParkourInfos.TranslateText(translator); 
        RoguelikeInfos.TranslateText(translator); 
        AttributeInfos.TranslateText(translator); 
        StageInfos.TranslateText(translator); 
        StageGroupInfos.TranslateText(translator); 
        HeroInfos.TranslateText(translator); 
        MonsterInfos.TranslateText(translator); 
        RoguelikeDropInfos.TranslateText(translator); 
        SkillInfos.TranslateText(translator); 
        SkillComposeInfos.TranslateText(translator); 
        EvolutionOptionInfos.TranslateText(translator); 
        ItemInfos.TranslateText(translator); 
        EquipInfos.TranslateText(translator); 
        EquipQualityInfos.TranslateText(translator); 
        EquipAttributeInfos.TranslateText(translator); 
        EquipAttributeWeightInfos.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

